obj = ArithmeticBrownianMotionWrapper_wrap.cxx _ArithmeticBrownianMotionWrapper.so

.PHONY: all
all: $(obj)

clean:
		rm -f *.o
		rm -f *.so
		rm -f *wrap*.c*
		rm -Rf build

ArithmeticBrownianMotionWrapper_wrap.cxx: ArithmeticBrownianMotionWrapper.i
		swig -python -c++ ArithmeticBrownianMotionWrapper.i

_ArithmeticBrownianMotionWrapper.so: ArithmeticBrownianMotionWrapper_wrap.cxx ArithmeticBrownianMotionWrapper.cpp
		python setup.py build_ext --inplace
